[th2-3147] removed sequence check inside batch, added check for timestamp between batches
th2-net/th2-mstore pull request #34
Opened 2022-02-03 19:49 UTC by andreydrobynin

…tamp between batches

2022-02-09 15:37 UTC, Nikita-Smirnov-Exactpro requested changes

2022-02-09 15:37 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/mstore/AbstractMessageStore.java
> +            long previousBatchLastSequence = sessionData.getAndUpdateLastSequence(lastSequence);
We must update sequence number and timestamps atomically

2022-02-09 15:37 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/mstore/AbstractMessageStore.java
> +                );
Please check isErrorEnabled before this operation

2022-02-09 15:37 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/mstore/MessageBatchStore.java
> +    protected Instant extractTimestamp(Message message) {
Maybe write Timestamp comparator to avoid convertation

2022-02-10 14:18 UTC, andreydrobynin commented on src/test/java/com/exactpro/th2/mstore/TestCaseMessageStore.java
> +    protected Timestamp toTimestamp(Instant timestamp) {
done

2022-02-11 15:09 UTC, Nikita-Smirnov-Exactpro approved these changes
Please redirect merge to the dev branch (pre release)

2022-03-01 14:51 UTC, Nikita-Smirnov-Exactpro requested changes

2022-03-01 14:51 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/mstore/AbstractMessageStore.java
> +                            previousBatchLast.getSequence()
```suggestion
                            previousBatchLast.getSequence(),
                            shortDebugString(messageBatch)

```

2022-03-01 14:51 UTC, Nikita-Smirnov-Exactpro commented on src/main/java/com/exactpro/th2/mstore/AbstractMessageStore.java
> +                            toInstant(previousBatchLast.getTimestamp())
```suggestion
                            toInstant(previousBatchLast.getTimestamp(),
                            shortDebugString(messageBatch))
```

2022-03-01 15:12 UTC, andrey-drobynin commented on src/main/java/com/exactpro/th2/mstore/AbstractMessageStore.java
> +                            toInstant(previousBatchLast.getTimestamp())
done

2022-03-01 16:08 UTC, Nikita-Smirnov-Exactpro approved these changes

2022-03-28 10:35 UTC, merged